#ifndef HEADER_H_ 
#define HEADER_H_ 
#include <stdio.h> 
#include <sys/types.h> 
#include <unistd.h> 
#include <wait.h> 
#include <signal.h> 
#include <sstream> 
#include <pthread.h> 
#include <stdlib.h> 
#include <time.h> 
#include <string.h> 
#include <ctype.h> 
#include <sys/time.h> 
#endif  /HEADER_H_*/
